[project]
name = "realworld-django-ninja"
version = "0.1"
dependencies = [
    "django>=5.0.6",
    "django-ninja>=1.1.0",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "django-stubs>=5.0.0",
]

